spring:
  application:
    name: security

server:
  port: 9930
  host: ${container.host:localhost}
  contextPath:

management:
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9900/eureka/}
  instance:
    preferIpAddress: true
    metadata-map:
      management.port: ${management.port:9930}

hystrix:
  threadpool:
    default:
      coreSize: 20
      maximumSize: 100
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 100